### ISSUE TITLE
S.Option.value and S.const

### ISSUE THREAD

**Issue by art-w** [dbuenzli/react#19]
The documentation states that `S.Option.value (Always x) s` is `x` whenever `s` is None. As such, if `s` is _always_ None, we would expect to get back `x`:

``` ocaml
let x, set_x = S.create 0
let s = S.const None           (* strange *)
(* let s, _ = S.create None *) (* correct *)

let o = S.Option.value ~default:(`Always x) s

let t = S.l2 (fun x o -> Printf.printf "x = %i, o = %i\n%!" x o) x o

let () = List.iter set_x [1;2]
```

Outputs:

```
x = 0, o = 0
x = 1, o = 0
x = 2, o = 0
```

If we switch `S.const` for `S.create`, we get the expected output:

```
x = 0, o = 0
x = 1, o = 1
x = 2, o = 2
```

This behaviour appears to be [tested](https://github.com/dbuenzli/react/blob/master/test/test.ml#L1215).

**Comment by dbuenzli** [comment]
Yes this is a bug. Somehow with these definitions we end up in [this case](https://github.com/dbuenzli/react/blob/d595442ef1b5c1fa2d8484c645ac3842ef84b572/src/react.ml#L1534) which seems right fine for `Init` (we only use it's value a creation time) but not for `Always` (which should follow the signal value).

> This behaviour appears to be tested.

C'est un comble !
