### ISSUE TITLE
"Update step" two-stepped update

### ISSUE THREAD

**Issue by art-w** [dbuenzli/react#20]
The update steps provide a nice mechanism for synchronizing primitive updates.  However, it has an odd semantics since the actual effects are splitted between updating the events/signals and propagating the change:

``` ocaml
let x, set_x = S.create "old" in
let s1 = Step.create () in
Printf.printf "x = %s\n%!" (S.value x) ; (* x = old *)
set_x ~step:s1 "new" ; (* do not propagate, but do update x *)
Printf.printf "x = %s\n%!" (S.value x) ; (* x = new *)
Step.execute s1; (* propagate *)
```

While this is perfectly documented, it seems counter-intuitive: The update steps interface gives the illusion that the updates are _synchrone_, but that's not really the case. If the update were delayed until the actual execution of the step, some edge cases would disappear:
- Currently, we can't prepare two update steps at the same time, since their update is effectful:

``` ocaml
let s1 = Step.create () in
let s2 = Step.create () in
set_x ~step:s1 "v1" ;
set_x ~step:s2 "v2" ; (* raises Invalid_argument "already scheduled" *)
```
- Calling `set_x ~step` inside another update step is totally unsafe: it lets us rewrite the current value (rather than raising an exception) which breaks the semantics and (may) trigger an error much later. If the affectation was delayed, the documentation would also be simpler since only `Step.execute` would really be unsafe and you wouldn't need to clarify the two-step affect/propagate process. (Well, the old api that doesn't require an explicit step would still be unsafe, since it calls `execute` under the hood.)

In general, React has quite a few edge cases that one needs to recall, and their description pollutes the documentation and adds to the cognitive burden. I'm not convinced that this one is necessary, it looks like an implementation detail rather than the expected semantic... Is there a use case where the current behaviour is useful?

(This is a minor issue, since React doesn't push you towards juggling with update steps, which explains why the step's affectations aren't noticeable at first sight. It has more to do with clean api design and simplifying the documentation.)

**Comment by dbuenzli** [comment]
> splitted between updating the events/signals and propagating the change:

Updating the *primitive* events/signals to be precise.

> Is there a use case where the current behaviour is useful ?

While what you suggest could be done. React tries as much as possible to be an efficient implementation of FRP, I think it's better if we avoid creating needless thunks for each primitive signal/event to update in a step only to wait for the eventual `Step.execute` that will be executed right after. This could become noticable if you have high-frequency changing values or thousands of primitives to schedule.

As you mention end-users are not supposed to use Steps so I don't mind the way this works. I would also suggest that if you are disturbed by this it may mean that you are not using the API as it should be used, which is basically the tight sequence create step, schedule primitive updates on the step, perform step.

Still the idea that by having a more atomic behaviour we could prepare more than one step at one time is an interesting one (especially if we think multicore), but it remains to be seen if really useful in practice.

**Comment by dbuenzli** [comment]
> Still the idea that by having a more atomic behaviour we could prepare more than one step at one time is an interesting one (especially if we think multicore), but it remains to be seen if really useful in practice.

So it may be worth mentioning in the docs that the state of a primitive between it's scheduling on a step and `Step.execute` is undefined to give us leeway to change the behaviour in the future.

**Comment by art-w** [comment]
Yeah, I agree that this isn't too much of a problem since React encourage you to call `Step.execute` right after the affectations. And sure, doing things imperatively is faster, but it should remain discrete considering that you still need to push all the updated nodes in the heap and propagate them.

Another trick that this could allow: Right now, calling `Step.execute` inside an update step is a bad idea, since it starts working right away. An alternative would be to schedule the step for later, at `t+dt`:

```ocaml
let event_fix f =
  let input, send = E.create () in
  let output, result = f input in
  let loop = E.fmap (fun v -> send v ; None) output in
  ignore (E.retain (fun () -> ignore loop) input) ;
  result
```

Of course, this is not good FRP style (it's an imperative hack), but it would be damn convenient when fixing an event require a lot of refactoring. It's also a common pitfall for beginners.

**Comment by dbuenzli** [comment]
I won't change this for now.
