### ISSUE TITLE
Research S.value alternatives.

### ISSUE THREAD

**Issue by art-w** [dbuenzli/react#21]
While using S.value isn't "good style" from a pure FRP perspective, some advanced tasks seems to benefit from it. I'm interested in use-cases like the ReactiveData library ([which uses it here for example](https://github.com/hhugo/reactiveData/blob/master/src/reactiveData.ml#L145).)

In practice, S.value raises in a rather random way, which makes it hard to structure the code so that it just works. Without a consistent S.value, we can't implement a simple "derivate" algorithm, since the initial value is unobservable.

```
val derive : t signal -> t * patch event
                         ^
                         requires S.value to work
```

The not-builtin snapshot/freeze function for signals allow us to write the less obvious:

```
t signal -> t signal * patch event
            ^^^^^^^^
            a constant signal which stores the value at time 0
```

which is a lot less convenient for the rest of the code base. For example, "integrating" the event patchs back into a signal of values ends up like:

``` ocaml
val integrate : t signal * patch event -> t signal

let integrate (initial, patches) =
  S.switch
    (S.fold
       (fun ts p -> S.map (apply_patch p) ts)
       initial
       patches)
```

while this would be trivial with a real value:

``` ocaml
let integrate initial patches =
  S.fold apply_patch initial patches
```

This pain is propagated to each function that works on the patched representation and it generates some confusion (we have to remember that the signal _must_ be constant to understand what's going on.) There are other examples where S.value is tempting (it's part of the library after all), and while it's always possible to find an alternative, it's not really worth the brain melting.

From a semantic perspective, it also means that signals (can) have an initial `Unitialized` value, followed by their first real value, and then potentially followed by their other values. The `S.changes` function doesn't let us observe the `Uninitialized -> Initialized` transition in the signal, since it happens _during_ an update step (it still is a change of value, just not one that's observable.) Ideally, the unset state shouldn't even exist, since it doesn't make any sense with the rest of the library!

Now, regarding the implementation, it sounds like `S.value` could "pull" the initial value when confronted with an uninitialized signal, rather than failing because the corresponding "push" hasn't been executed yet. Is there a situation where this would fail?

(To clarify, I have `node.update (Step.find_unfinished node)` in mind, but I don't fully understand the React codebase, so it might not be enough (?))

---

**edit:** I somehow missed the simpler:

``` ocaml
S.bind initial (fun t -> S.fold apply_patch t patches)
```

So the collections' example might be workable without S.value after all. Still, it would be nicer if it worked properly :) .

**Comment by dbuenzli** [comment]
> Now, regarding the implementation, it sounds like S.value could "pull" the initial value when confronted with an uninitialized signal, rather than failing because the corresponding "push" hasn't been executed yet. Is there a situation where this would fail?

I think this would be insane to implement (it's really imperative hell down there) somehow requiring the simple topological update performed now to be done in piece wise fashions according to the node you request the value from (remember you may then be in the update loop while you invoke `S.value`). Besides I didn't think much about it but it's unclear whether it can really be implemented in a sound way (I'm thinking about delayed nodes). 

> S.bind initial (fun t -> S.fold apply_patch t patches)
> So the collections' example might be workable without S.value after all. Still, it would be nicer if it worked properly :) 

Beautiful oneliner... What doesn't work here ?

**Comment by art-w** [comment]
Hmm, I'm not sure why this should affect the "push" system already in place, pulling should do its own (implicit) reverse topological sort on the nodes.  It's pretty much falling back to the simplest (inefficient) FRP implementation possible:

```ocaml
type node =
  { mutable value : 'a option
  ; mutable set : bool
  ; update : unit -> 'a option }
let pull node =
  if node.set
  then node.value
  else begin
    node.set <- true ;
    node.value <- node.update () ;
    node.value
  end
```

As long as events/signals don't make assumptions regarding the fact that their inputs have been updated (meaning that they go though `S.value` and uh, not `!(m.ev)` for events since they may need to pull (*)), and `Step.execute.update` checks that the node hasn't been processed before updating it, I don't see why this wouldn't work. Pulling doesn't care about the push system, it just stops when it hits an already defined node. Pushing doesn't care either if someone else update the nodes for him, as long as its heap has been populated.  Both of them respect the synchrone semantics of FRP, and leave the graph in a coherent state for the other to work with. But I agree this is a bit sketchy and there are some infernal details inside React that I haven't looked at close enough. (For delayed nodes, I believe they should just return their currently stored value.)

(*) This could be optimized by adding an `is_pull : bool` inside `step`, such that the `update` functions would know if they really need to pull (since that's not the general case.) Pulling can also abort early when the node has a lower rank than the heap minimum (since it would have been pushed.)

> Beautiful oneliner... What doesn't work here ?

Well, signals are infectious since we can't get out of them. For example, if we wanted to cleanup the patchs, to reduce their size for later in the system, we would need some access to the initial value to integrate eventfully:

```ocaml
val cleanup_patch : data -> patch -> patch option
(** attempt to reduce the patch size / remove it *)

S.bind initial (fun t ->
  E.Option.value
    (E.l1 snd
      (E.fold
        (fun (t, _) p -> match cleanup_patch t p with
          | None -> t, None
          | Some p' -> apply_patch p' t, Some p')
        t
        patchs)))
```

Another situation where this happens is converting between two patchs representation, like going from a `patch_array` (with `Remove_at of index`) to a `patch_set` (with `Remove_elt of 'a`).

So now patchs should have type `patch event signal` and we have to use `S.switch (S.l2 ... initial patchs)`. I mean, it's workable, but it's not convenient when you discover the implications later. `S.value` is very tempting in many situations, and the workarounds obscure the code and intent -- right now, `S.value` isn't doing much and should be ignored (despite its prominent placement in the documentation, and the lack of a `freeze/snapshot` to guide you in the right direction.)

**Comment by dbuenzli** [comment]
I'm not denying this can't be done. 

However as you mention this is something programmers will be *very* tempted to use. The problem is that the pull approach can be in practice quite expensive (you have to explore the whole dependency graph backwards) and this could come up randomly because e.g. the inputs are such that they did form such an expensive graph dynamically.

The result is that people hiding uses of S.value in their own derived abstractions will lead to sub-optimal update steps and an unpredictable cost model.

> and the lack of a freeze/snapshot to guide you in the right direction

What do you mean by that ? I do not pretend React provides the right set of combinators and I'm always willing to provide what feels is missing, if there's a good rationale for it.

**Comment by art-w** [comment]
I agree it would be bad if people started pulling everywhere, rather than using `S.value` sporadically like in the collection-patching example.

Unless I'm missing something obvious, writing `freeze/snapshot` is a bit edgy:

```ocaml
let always _ _ = true

let static_freeze s = (* fails if called inside an update step *)
  let x = S.l1 ~eq:always (fun v -> v) s in
  S.stop x ;
  x

let dynamic_freeze s = (* fails if called outside an update step *)
  let rec x = lazy (S.l1 ~eq:always (fun v -> S.stop (Lazy.force x) ; v) s) in
  Lazy.force x

let freeze s = (* ... ok? *)
  let value = ref None in
  let rec x =
    lazy (S.l1 ~eq:always
            (fun v -> match !value with
               | None -> value := Some v ; v
               | Some v -> S.stop (Lazy.force x) ; v)
            s) in
  Lazy.force x

(* or we can just keep it live *)
let freeze s = S.l1 ~eq:always (fun v -> v) s
```

**Comment by dbuenzli** [comment]
> Unless I'm missing something obvious, writing freeze/snapshot is a bit edgy

I cannot tell you until you write down the *semantics* for me... I have a vague idea of what `freeze` would do no but no idea of what `snapshot` would (is that `S.sample` ?). But in general if you need to use `S.stop` or reference cells to implement a combinator that has a reasonable semantics it really means that React is missing something or that it should be a primitive combinator (`S.stop` should rather be used to manage the side effectful signals you have at the edge of the dependency graph).

Also it seems to me that freeze would benefit of being a primitive since in many cases we should be able to optimize it to a `Const` signal (which can the propagate in the graph thanks to smart constructors).

**Comment by art-w** [comment]
Well, `S.stop` is a small optimization to get to the desired semantic, we can do without. I wasn't attentive and thought it would introduce some `Const` equivalent, but that's just not how smart constructors works :) .
```
[freeze e]_t = [e]_0 forall t >= 0
  where 0 is [freeze e] creation time
```
`snapshot` is a more conventional name for this combinator in the literature (but you used [freeze](https://github.com/dbuenzli/react/blob/master/TODO.md#new-signal-combinators) in your TODO.)

**Comment by dbuenzli** [comment]
> snapshot is a more conventional name for this combinator in the literature (but you used freeze in your TODO.)

Ah indeed this is in the TODO... so... it should be done (sorry I tend to forget the things I'm not currently in). I guess the idea was that `freeze`+ `bind` could be useful as a substitution to `S.value`.

**Comment by dbuenzli** [comment]
The [`note` library](https://github.com/dbuenzli/note/#history) has a `S.value` that is safe to use.
