### ISSUE TITLE
Installation without opam

### ISSUE THREAD

**Issue by romildo** [dbuenzli/react#25]
I want to install `react` on Windows, where `opam` is not available. Please give instructions on how it can be done easily. If possible, include a Makefile for that purpose in the distribution.

**Comment by dbuenzli** [comment]
Install instructions are in the readme. No `Makefile` will be included.

**Comment by dbuenzli** [comment]
Btw. you may want to give a try at [this](https://github.com/dra27/opam/tree/windows) `opam` branch. It may not get you a fully functional `opam` yet but it may give you a fully functional `opam-installer` binary that you can use to process the `.install` file.

**Comment by romildo** [comment]
The install instructions are not suitable for Windows users. As `opam` is not available for Windows probably the user does not know about it and how to use it either.

The instructions just say to do `opam install react` or consult the `opam` file for build instructions.

I think those instructions are not helpful for students that is just starting to learn OCaml and needs this library as a dependency for other packages (like Merlin).

**Comment by dbuenzli** [comment]
Unfortunately given the number of packages I distribute I can't rely on ad-hoc procedures for them and this is why I rely on opam `.install` files. 

Note that the `.install` format is simple and [well-documented](https://opam.ocaml.org/doc/manual/dev-manual.html#sec25) so you are more than welcome to contribute a program that handles them on Windows without needing `opam`; this would allow you to support the installation of all the software [listed here](http://erratique.ch/software).  

`opam` on Windows is soon or later going to become a reality so I personally don't won't to loose my time on this (btw. AFAIK react is not needed for merlin).

**Comment by romildo** [comment]
Sorry. I meant `utop`.
