### ISSUE TITLE
event stream hangs for some reason

### ISSUE THREAD

**Issue by Freyr666** [dbuenzli/react#27]
I'm trying to use event streams to map a stream of messages appearing in socket to the streams of db writings, notifications through websockets and so on. Everything was fine till I've added websocket support. After that the whole event stream started to hang on frequently appearing big messages. The problem appears only then I use websockets, though I suspect that it might be caused by some react's invariant being broken due to heavy computations or something else. 

I've described the issue more verbosely here [1] and I hope you would introduce some clarity concern what may cause such issues. Thank you. 

[1] https://github.com/vbmithr/ocaml-websocket/issues/95

**Comment by dbuenzli** [comment]
Sorry I don't have the time to help you to debug your programs. There are too much layers involved (e.g. `lwt` whose `react` interaction I always found dubious) for me to tell you anything meaningful. Please do not open issue unless you have a clear suspicion the bug is with `react`.

**Comment by dbuenzli** [comment]
You may get some help from other people on http://discuss.ocaml.org

**Comment by Freyr666** [comment]
Ok, I'll try to find out what exactly causing the issue.

**Comment by dbuenzli** [comment]
I had a quick look, I suspect there's no hang, it's just that your events gets gc'd. See react documentation [here](http://erratique.ch/software/react/doc/React.html#sideeffects).

**Comment by Freyr666** [comment]
Oh, indeed they are! Thank you very very much.
