### ISSUE TITLE
Subtyping of reactive values

### ISSUE THREAD

**Issue by rand00** [dbuenzli/react#29]
I've been in a situation in my codebase where I wanted subtyping of reactive values. I solved it by making a new event of the supertype, but this is not as elegant.

My guess is that it is not possible to solve this with the current implementation (using references) + OCamls typesystem, as it makes the reactive type invariant.

I had an idea where I wondered wether OCaml's typesystem could be made to track the usage of the references internel to a module with an abstract type definition, and then not restrict the abstract type to be invariant. 
This would let someone making a library able to use whatever implementation deemed neccesary, and not restrict the types exposed. 

I also wonder whether the tracking of locality of references in function bodies, in the OCaml effects branch, would be able to solve this... 

The semantics I would want of reactive values (the type `'a t` is the analogue to e.g. `'a E.t`):
``` ocaml
type ab = [ `A | `B ]
type b = [ `B ]
type 'a t = T of 'a | TEmpty

let f : 'a t list -> 'a t = function
  | hd :: _ -> hd
  | [] -> TEmpty

let this_works =
  let a : ab t = T `A in
  let b :  b t = T `B in
  f [ a; (b: b t :> ab t) ]
```
What doesn't work:
``` ocaml
module type S = sig
  type +'a t
  val v : 'a -> 'a t
  val fl : 'a t list -> 'a t
end
  
module T : S = struct
  type +'a t = T of ('a ref) | TEmpty
  let v x = T (ref x)
  let fl = function
    | hd :: _ -> hd
    | [] -> TEmpty
end

(* Error: In this definition, expected parameter variances are not satisfied.
 *        The 1st type parameter was expected to be covariant,
 *        but it is injective invariant. *)

```

**Comment by dbuenzli** [comment]
Indeed given the current implementation it seems difficult to get the variance annotation you'd like.
