### ISSUE TITLE
S.sample seems to re-trigger its event when signal's value changes

### ISSUE THREAD

**Issue by Sventimir** [dbuenzli/react#30]
Consider the following example:

```
let (event, trigger) = React.E.create ()
let (activated, activate) = React.E.create ()

let s = React.S.fold (+) 0 event

let handle i =
    trigger 1;
    print_int i

let trace = React.E.trace handle (React.S.sample (fun () e -> e) activated s)
```
After having loaded the above to `utop` and calling `activate ()`, the program seems to fall into an infinite loop. The only explanation I can come to is that `S.sample` considers the `event` to "last" until `handle` finishes and since the latter updates `s`, `S.sample` in turn triggers `E.trace` with new value.

Is this behavior intentional? From my point of view it looks more like a bug.

**Comment by dbuenzli** [comment]
Your tracing function `handle` is `trigger`ing. Firstly you are not allowed to do this see the warning [here](http://erratique.ch/software/react/doc/React.E.html#VALcreate). Second you actually just created an infinite loop.
