### ISSUE TITLE
Project Name

### ISSUE THREAD

**Issue by superherointj** [dbuenzli/react#31]
Considering React (JS / UI framework/library) became quite wide spread. While OCaml's FRP React exists for quite some time and has not gained much popularity. And this trend probably won't be reversed. Just as Jbuilder tool name was confusing to most people (because of Java's much more widespread tool), changing name to Dune (a different unrelated name) was nice. Would be nice if React (OCaml's FRP) had it's name changed to something more descriptive and less confusing to newcomers.

**Comment by dbuenzli** [comment]
I think the churn this would incur on existing users of the library doesn't make this worth changing in order "to be less confusing to newcomers."

**Comment by superherointj** [comment]
Fair enough. At least on community open source projects, I could help in getting it updated if the name change would be considered. I see it as "debt". Pay now or pay daily. Of course, you have already decided. Just saying I was willing to help.

**Comment by dbuenzli** [comment]
> I see it as "debt". Pay now or pay daily.

I guess each has its own view :-) personally I see nothing to *pay* here... Meaningful names come up in finite quantity, clashes exists, it's not a big deal.
