### ISSUE TITLE
Triggering send when an event occurs without calling from within an update step

### ISSUE THREAD

**Issue by roddyyaga** [dbuenzli/react#33]
I would like to do something like this
```ocaml
open React

let x1, send_x1 = E.create ()
let x2, send_x2 = E.create ()
let x3, send_x3 = E.create ()
let y1, send_y1 = E.create ()
let y2, send_y2 = E.create ()
let y3, send_y3 = E.create ()

let connect x send_y = E.map (fun () -> send_y ()) x

let (_ : unit event) = connect x1 send_y1
let (_ : unit event) = connect x1 send_y2
let (_ : unit event) = connect x1 send_y3
let (_ : unit event) = connect x2 send_y2
let (_ : unit event) = connect x3 send_y2
```

but as I understand it it is forbidden to call send in the `E.map` function. Is there another way of getting this kind of behaviour?

**Comment by dbuenzli** [comment]
Hello, questions are welcome but better asked and answered on the [ocaml forum](https://discuss.ocaml.org/). 

If you want to do something like this you need to make sure that your side effecting events do not trigger a new update cycle. One way of acheiving this is to deposit the effects in a queue of thunks from which you pull and execute once the update cycle has ended.
