### ISSUE TITLE
react.1.2.1 build for OCaml 5.00.0+trunk

### ISSUE THREAD

**Issue by shakthimaan** [dbuenzli/react#37]
The `Pervasives` module has been deprecated in OCaml 5.00.0+trunk, and the recommendation is to use `Stdlib` instead. react.1.2.1 builds fine for OCaml 5.00.0+trunk with this change. 

Would it be possible for you to review the patch, or suggest any other alternative?

**Comment by dbuenzli** [comment]
Sorry I forgot to push the repo. Your wish happened two days ago https://github.com/ocaml/opam-repository/pull/20707
